### ISSUE TITLE
Ticks Per Second Are Low

### ISSUE THREAD

**Issue by mcmso** [jredfox/mc-dpifix#1] opened 2024-12-23 14:35 UTC
Hello, I am not very familiar with coding, but when I was trying to solve the low TPS problem by deleting parts of the mod, I found that deleting dpifix causes the game to fail to start.https://paste.ubuntu.com/p/43gVFZCCFK/

**Comment by mcmso** [comment] 2024-12-23 14:46
I'm not saying that your mod has any flaws. On the contrary, it runs very well and solves the problem of camera twisting in 1.7.10.

**Comment by jredfox** [comment] 2024-12-24 10:27
> I'm not saying that your mod has any flaws. On the contrary, it runs very well and solves the problem of camera twisting in 1.7.10.

Camera Twisting fix should only be applied on windows not linux. If it somehow fixes it then it's a driver issue. sadly drivers in linux remain very buggy unless the OEM was designed specifically for linux in most cases from my experiences on ubuntu / linux mint but especially on ubuntu

I need to know the exact java distro your using and mod list. What launcher your using etc. Because I tested linux mint and was uneable to reproduce such an error. Do you have an anti virus software try disabling it redownloading the mod and see if it fixes it?

**Comment by jredfox** [comment] 2024-12-24 10:33
Do you mean Ticks per Second? This mod shouldn't cause it especially on anything above 1.6x where no actual tick hooks are happening. **I need a full mod list the launcher and steps to reproduce in case something weird or unexpected is happening**. Are you using something like sponge forge which isn't even forge at all I need steps to reproduce

Does Disable config option called `CoreMod.Enabled` in the config fix the issue? It will disable all coremod functionality while still fixing DPI and setting the process priority.

Does removing the mod fix the issue? If not then it's not my mod's issue and the issue will be closed

These options below are what the coremod can do in 1.7.10 or higher **Note CoreMod.Enabled Has to be true first**:
```
Coremod.FullScreen.MouseFix.Linux=true
Coremod.FullScreen.MouseFix.OtherOS=false
Coremod.FullScreen.ResizeableFix=true
Coremod.FullScreen.SaveFix=true
Coremod.FullScreen.SplashFix=true
Coremod.FullScreen.TabFix=true
Coremod.GUI.ModLogoFix=true
Coremod.GUI.MouseFix=true
```

**Comment by mcmso** [comment] 2024-12-24 14:12
> 你的意思是每秒滴答数吗？这个 mod 不应该导致这种情况，特别是在 1.6x 以上没有实际滴答钩子发生的情况下。**我需要一个完整的 mod 列表启动器和重现步骤，以防发生奇怪或意外的事情**。你使用的是像海绵锻造这样的东西吗？它根本不是锻造。我需要重现步骤
> 
> 在配置中调用的“禁用配置”选项是否可以`CoreMod.Enabled`解决问题？它将禁用所有 coremod 功能，同时仍修复 DPI 并设置进程优先级。
> 
> 删除 mod 能解决问题吗？如果不能，那么这不是我的 mod 的问题，问题将被关闭
> 
> 下面这些选项是 coremod 在 1.7.10 或更高版本中可以执行的操作**注意 CoreMod.Enabled 必须首先为真**：
> 
> ```
> Coremod.FullScreen.MouseFix.Linux=true
> Coremod.FullScreen.MouseFix.OtherOS=false
> Coremod.FullScreen.ResizeableFix=true
> Coremod.FullScreen.SaveFix=true
> Coremod.FullScreen.SplashFix=true
> Coremod.FullScreen.TabFix=true
> Coremod.GUI.ModLogoFix=true
> Coremod.GUI.MouseFix=true
> ```



> Do you mean Ticks per Second? This mod shouldn't cause it especially on anything above 1.6x where no actual tick hooks are happening. **I need a full mod list the launcher and steps to reproduce in case something weird or unexpected is happening**. Are you using something like sponge forge which isn't even forge at all I need steps to reproduce
> 
> Does Disable config option called `CoreMod.Enabled` in the config fix the issue? It will disable all coremod functionality while still fixing DPI and setting the process priority.
> 
> Does removing the mod fix the issue? If not then it's not my mod's issue and the issue will be closed
> 
> These options below are what the coremod can do in 1.7.10 or higher **Note CoreMod.Enabled Has to be true first**:
> 
> ```
> Coremod.FullScreen.MouseFix.Linux=true
> Coremod.FullScreen.MouseFix.OtherOS=false
> Coremod.FullScreen.ResizeableFix=true
> Coremod.FullScreen.SaveFix=true
> Coremod.FullScreen.SplashFix=true
> Coremod.FullScreen.TabFix=true
> Coremod.GUI.ModLogoFix=true
> Coremod.GUI.MouseFix=true
> ```

It works fine when adding this mod, but an error occurs when removing the mod
https://paste.ubuntu.com/p/43gVFZCCFK/

**Comment by jredfox** [comment] 2024-12-24 14:30
> It works fine when adding this mod, but an error occurs when removing the mod https://paste.ubuntu.com/p/43gVFZCCFK/

This is because you deleted classes inside the mod. Redownload it!

Give me your mod list and steps to reproduce the crash is caused from yourself not the actual ticking issue you have.

**Comment by jredfox** [comment] 2024-12-24 15:09
I also saw unicode characters in your `.minecraft` instance path. MultiMC / Prism both crash without any mods installed on the unicode path. Curseforge / Vanilla don't seem to support multiple instances in different paths. So what launcher are you using to even get unicode paths to launch at all without any mods. AT launcher disallows Unicode altogether and the rest of the "launchers" don't work with 1.12.2 or lower very well.

1. Give me your mod list (a list of folders in your mods folder) or simply upload it to medifire.com and send me a link
2. Use ANSII characters only in your path no asian or non english characters no launcher seems to support it
3. I highly doubt this has anything to do with DPI-Fix as there are no ticking hooks in the mod it's most likely another mod. So if it 
4. What monitor are you using is it in 4k or higher? You need to use optifine and change the fullscreen resolution in game to be lower or upgrade your graphics card. 

The only reason why DPI-Fix would effect Ticking is because it increases the resolution to the actual resolution of the game. If your monitor is in 8k or even 4k then the game will render in 4k. To work around this you can install optifine which is officially supported and change the full in game screen's resolution to something smaller to get better FPS which also results in higher Ticks Per Second. **NOTE: if you install optifine the fullscreen resoultion you have to hit F+11 the maximize button will be in windowed mode and render in whatever window size your in**. This is because it's a limit of LWJGL 2 not supporting window mode virtual resolutions. In matter of fact LWJGL 3 also seems to struggle with it

**Comment by mcmso** [comment] 2024-12-24 15:12
> I also saw unicode characters in your `.minecraft` instance path. MultiMC / Prism both crash without any mods installed on the unicode path. Curseforge / Vanilla don't seem to support multiple instances in different paths. So what launcher are you using to even get unicode paths to launch at all without any mods. AT launcher disallows Unicode altogether and the rest of the "launchers" don't work with 1.12.2 or lower very well.
> 
> 1. Give me your mod list (a list of folders in your mods folder) or simply upload it to medifire.com and send me a link
> 2. Use ANSII characters only in your path no asian or non english characters no launcher seems to support it
> 3. I highly doubt this has anything to do with DPI-Fix as there are no ticking hooks in the mod it's most likely another mod. So if it
> 4. What monitor are you using is it in 4k or higher? You need to use optifine and change the fullscreen resolution in game to be lower or upgrade your graphics card.
> 
> The only reason why DPI-Fix would effect Ticking is because it increases the resolution to the actual resolution of the game. If your monitor is in 8k or even 4k then the game will render in 4k. To work around this you can install optifine which is officially supported and change the full in game screen's resolution to something smaller to get better FPS which also results in higher Ticks Per Second.

Please leave your contact information. My network communication tool is only discord, which will improve the speed of communication

**Comment by jredfox** [comment] 2024-12-24 15:13
https://discord.gg/qdewa8E

**Closed as completed** 2024-12-24 18:49 UTC
Labels: invalid, unable to reproduce
